---
- name: prepare host agent installation
  hosts: localhost
  become: yes
  vars:
    sar_url: "http://65.108.157.137:8000/sap/SAPHOSTAGENT02_2-10009320.SAR"
    sarcar_url: "http://65.108.157.137:8000/sap/SAPCAR_1324-80000935.EXE"
    path: "/opt/sap"
  tasks:
    - name: create directory to store SAP artifacts
      file:
        path: "{{ path }}"
        state: directory
    - name: Download the SAR
      get_url: 
        url: "{{ sar_url }}"
        dest: "{{ path }}"

    - name: Download the SAPCAR
      get_url: 
        url: "{{ sarcar_url }}"
        dest: "{{ path }}"
      

- name: Host Agent Installation
  hosts: hanas
  become: yes

  vars:
    sarcar_url: "http://65.108.157.137:8000/sap/SAPHOSTAGENT02_2-10009320.SAR"
    sar_url: "http://65.108.157.137:8000/sap/SAPCAR_1324-80000935.EXE"
    sap_hostagent_installation_type: "sar"
    sap_hostagent_sar_local_path: "/opt/sap"
    sap_hostagent_sar_file_name: "SAPHOSTAGENT02_2-10009320.SAR"
    #sap_hostagent_sar_file_name: "SAPHOSTAGENT02_2-10009320.SAR"
    sap_hostagent_sapcar_local_path: "/opt/sap"
    #sap_hostagent_sapcar_file_name: "SAPCAR_1311-80000935.EXE"
    sap_hostagent_sapcar_file_name: "SAPCAR_1324-80000935.EXE"
    sap_hostagent_clean_tmp_directory: true
      
  roles:
    - redhat_sap.sap_hostagent

