---
- hosts: hanas
  vars:
    rhn_username: test
    rhn_password: test
    rhn_poolid: test
  pre_tasks:
    - name: Register and subscribe to a pool for sap installation
      redhat_subscription:
        state: present
        username: "{{ rhn_username }}"
        password: "{{ rhn_password }}"
        pool_ids: "{{ rhn_poolid }}"
        force_register: yes
  roles:
    - redhat_sap.sap_rhsm

