- hosts: hanas

  vars:
    sap_preconfigure_fail_if_reboot_required: no
    sap_hana_preconfigure_fail_if_reboot_required: no
    sap_hana_preconfigure_update: yes

  roles:
    - role: sap-preconfigure
    - role: sap-hana-preconfigure


