---

- hosts: hanas

  vars:
    storage_safe_mode: false
    storage_pools:
      - name: sap
        disks: pmem0
        volumes:
          - name: data
            size: "200 GiB"
            mount_point: "/hana/data"
            fs_type: xfs
            state: present
          - name: log
            size: "200 GiB"
            mount_point: "/hana/log"
            fs_type: xfs
            state: present
          - name: shared
            size: " 200 GiB"
            mount_point: "/hana/shared"
            fs_type: xfs
            state: present
          - name: sap
            size: "200 GiB"
            mount_point: "/usr/sap"
            state: present

  roles:
    - rhel-system-roles.storage
